name: Deploy to server

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build dist
    runs-on: ubuntu-latest
    if: gitea.repository == 'MultiMote/niimblue'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "25"
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check code
        run: npm run sv-check

      - name: Build
        run: npx vite build --base="/"
        env:
          COMMIT_HASH: ${{gitea.sha}}

      - name: Generate Sitemap
        run: |
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
          <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">
            <url>
              <loc>$DEPLOY_URL</loc>
              <lastmod>$LAST_MODIFIED</lastmod>
            </url>
          </urlset>" > ./dist/sitemap.xml
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          LAST_MODIFIED: ${{ gitea.event.repository.updated_at }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        env:
          GITHUB_SERVER_URL: 'https://github.com'
        with:
          name: niimblue-dist
          path: dist/

  deploy-server-1:
    name: Deploy to Main Server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build
        uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: niimblue-dist
          path: dist/

      - name: Setup rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with Rsync
        run: |
          rsync -avz --delete \
                -e "ssh -p ${{ secrets.SSH_PORT || 22 }}" \
                ./dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/${{ gitea.head_ref || gitea.ref_name }}/

  deploy-server-2:
    name: Deploy to Second Server
    needs: build
    runs-on: ubuntu-latest
    if: gitea.ref_name == 'main'
    steps:
      - name: Download Build
        uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: niimblue-dist
          path: dist/

      - name: Setup rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p ${{ secrets.SSH_PORT_2 || 22 }} ${{ secrets.SSH_HOST_2 }} >> ~/.ssh/known_hosts

      - name: Deploy with Rsync
        run: |
          rsync -avz --delete \
                -e "ssh -p ${{ secrets.SSH_PORT_2 || 22 }}" \
                ./dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_2 }}:${{ secrets.DEPLOY_PATH_2 }}/${{ gitea.head_ref || gitea.ref_name }}/

  upload-dist-to-github:
    name: Update GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: gitea.ref_name == 'main'
    steps:
      - name: Download Build
        uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: niimblue-dist
          path: niimblue-dist/

      - name: Zip niimblue-dist
        working-directory: niimblue-dist
        run: zip -r ../niimblue-dist.zip *

      - name: Setup GitHub CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1
        with:
          gh-cli-version: 2.72.0

      - name: Update GitHub release
        run: gh release upload snapshot niimblue-dist.zip -R MultiMote/niimblue --clobber
        env:
          GH_TOKEN: ${{ secrets.GH_UPLOAD_TOKEN }}

